### ISSUE TITLE
Is the pose of the images available?

### ISSUE THREAD

**Issue by b0ku1** [microsoft/DigiFace1M#5]
hi there,

Thanks for releasing this awesome dataset. I'm wondering if the head pose of each image is available as well? It would be very helpful for different kinds of research.

Thanks.

**Comment by friggog** [comment]
Hi - thanks for the interest in the dataset, unfortunately this release is intended to accompany the WACV paper submission and we only have approval to release the images as they are - we are not planning to include additional types of ground truth or images. We'll take your suggestions into consideration for any future dataset releases.
