### ISSUE TITLE
Landmarks

### ISSUE THREAD

**Issue by pranavmalikk** [microsoft/DigiFace1M#7]
Will landmarks or semantic segmenation for these faces be released?

**Comment by lingkangjie** [comment]
Can you release ground-truth facial landmarks for aligning the faces?

**Comment by iperov** [comment]
why do you need landmarks if faceset with resolution 112x112 is completelly useless

**Comment by friggog** [comment]
Hi - thanks for the interest in the dataset, unfortunately this release is intended to accompany the WACV paper submission and we only have approval to release the images as they are - we are not planning to include additional types of ground truth or images. We'll take your suggestions into consideration for any future dataset releases.
